[hack]
exten => _X.,1,NoOp(hack: dialing PJSIP/${EXTEN})
 same => n,Dial(PJSIP/${EXTEN},30)
 same => n,Hangup()

exten => 8500,1,VoiceMailMain()
 same => n,Goto(s,6)

exten => 600,1,Playback(demo-echotest)
 same => n,Echo()
 same => n,Playback(demo-echodone)
 same => n,Goto(s,6)
