[global]
default-realm=nottinghack.org.uk
debug=yes

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0
tcp_keepalive_enable=yes
tcp_keepalive_idle_time=30
tcp_keepalive_interval_time=10
tcp_keepalive_probe_count=5

[aor-single](!)
type=aor
max_contacts=4

[7883]
type=endpoint
context=hack
allow=all
aors=7883

[7883]
type=auth
auth_type=userpass
username=7883
password=7883

[7883](aor-single)

[0275]
type=endpoint
context=hack
allow=all
aors=0275

[0275]
type=auth
auth_type=userpass
password=0275
username=0275

[0275](aor-single)



[acl]
type=acl
deny=0.0.0.0/0.0.0.0
permit=10.0.0.0/24  ;; vlan 2
permit=10.0.8.0/24  ;; vpn
