[global]
default-realm=nottinghack.org.uk

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0
tcp_keepalive_enable=yes
tcp_keepalive_idle_time=30
tcp_keepalive_interval_time=10
tcp_keepalive_probe_count=5

[aor-single](!)
type=aor
max_contacts=4

[acl]
type=acl
deny=0.0.0.0/0.0.0.0
permit=10.0.0.0/24  ;; vlan 2
permit=10.0.8.0/24  ;; vpn
permit=127.0.0.1/32

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Sipcord
[sipcord]
type = registration
transport = transport-udp
outbound_auth = sipcord
server_uri = sip:127.0.0.1:5066
client_uri = sip:1000@nottinghack.org.uk
retry_interval = 60
expiration = 3600
auth = sipcord

[sipcord]
type = endpoint
context = sipcord
aors = sipcord
allow = all
from_user = sipcord
from_domain = nottinghack.org.uk
outbound_auth = sipcord

[sipcord]
type = auth
auth_type = userpass
username = sipcord
password = sipcord

[sipcord]
type = aor
contact=127.0.0.1:5066

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Studio Polycom SoundPoint 331 - 7883 / STUD
[7883]
type=endpoint
context=hack
allow=all
aors=7883

[7883]
type=auth
auth_type=userpass
username=7883
password=7883

[7883](aor-single)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Aaron - 0275 / 0ASJ
[0275]
type=endpoint
context=hack
allow=all
aors=0275

[0275]
type=auth
auth_type=userpass
password=0275
username=0275

[0275](aor-single)


